TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_LEFTCTRL
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL
  - KEY: KEY_LEFTSHIFT
    TAP: [ KEY_LEFTSHIFT, KEY_9, ]
    HOLD: KEY_LEFTSHIFT
  - KEY: KEY_RIGHTSHIFT
    TAP: [ KEY_RIGHTSHIFT, KEY_0, ]
    HOLD: KEY_RIGHTSHIFT
  - KEY: KEY_LEFTCTRL
    TAP: [ KEY_LEFTSHIFT, KEY_LEFTBRACE, ]
    HOLD: KEY_LEFTCTRL
  - KEY: KEY_RIGHTCTRL
    TAP: [ KEY_RIGHTSHIFT, KEY_RIGHTBRACE, ]
    HOLD: KEY_RIGHTCTRL
  - KEY: KEY_ESC
    TAP: KEY_CAPSLOCK
    HOLD: KEY_CAPSLOCK
